/*
# Expand database - Batch 2c: Government policies

## Summary
Adds 30 important Indian government policies covering rights, laws, and
governance frameworks that citizens should know about.

## Notes
- Uses ON CONFLICT (slug) DO NOTHING for idempotency.
- No destructive operations; pure INSERT.
*/

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'policies_slug_key') THEN
    ALTER TABLE policies ADD CONSTRAINT policies_slug_key UNIQUE (slug);
  END IF;
END $$;

INSERT INTO policies (title, slug, category, summary, content, key_points, official_reference, tags, published, last_verified_at, faq_list)
VALUES
('Right to Education (RTE) Act', 'right-to-education-act', 'Education',
 'The RTE Act guarantees free and compulsory education to all children aged 6-14.',
 'The Right of Children to Free and Compulsory Education (RTE) Act, 2009 guarantees free and compulsory education to all children aged 6-14 years. It mandates that 25% of seats in private schools be reserved for economically disadvantaged students.',
 '["Free education for children aged 6-14","25% reservation in private schools for EWS","No capitation fee or screening test","Trained and qualified teachers","Infrastructure norms for schools","No child held back or expelled until Class 8"]',
 'RTE Act, 2009 (Act 35 of 2009)',
 '["education","rte","right","children","free","compulsory"]', true, now(), '[]'),
('National Education Policy 2020', 'national-education-policy-2020', 'Education',
 'NEP 2020 transforms Indian education with a 5+3+3+4 structure and multidisciplinary approach.',
 'The National Education Policy (NEP) 2020 envisions a comprehensive overhaul of the Indian education system. It introduces a 5+3+3+4 pedagogical structure, multidisciplinary education, multiple entry/exit options, and mother tongue instruction until Class 5.',
 '["5+3+3+4 structure (Foundational, Preparatory, Middle, Secondary)","Mother tongue instruction until Class 5","Multiple entry and exit in higher education","4-year integrated teacher education","Single regulator for higher education (HECI)","Target: 50% GER in higher education by 2035"]',
 'NEP 2020 (Ministry of Education, GoI)',
 '["education","nep","policy","reform","multidisciplinary"]', true, now(), '[]'),
('Consumer Protection Act 2019', 'consumer-protection-act-2019', 'Rights',
 'The Consumer Protection Act 2019 strengthens consumer rights with e-commerce rules and CCPA.',
 'The Consumer Protection Act, 2019 replaced the 1986 Act. It establishes the Central Consumer Protection Authority (CCPA), covers e-commerce, product liability, and direct selling. Consumers can file complaints online and seek faster redressal.',
 '["CCPA for class action and enforcement","E-commerce rules for online shopping","Product liability for defective goods","Mediation as dispute resolution","No fee for complaints up to Rs. 5 lakh","Video conferencing for hearings"]',
 'Consumer Protection Act, 2019 (Act 35 of 2019)',
 '["consumer","rights","protection","ecommerce","ccpa","liability"]', true, now(), '[]'),
('Right to Information Act 2005', 'right-to-information-act-2005', 'Rights',
 'The RTI Act empowers citizens to request information from public authorities.',
 'The Right to Information (RTI) Act, 2005 empowers Indian citizens to request information from public authorities. It mandates timely response (within 30 days) and promotes transparency and accountability in governance.',
 '["Any citizen can file RTI","Application fee: Rs. 10 (central)","Response within 30 days (48 hours if life/liberty)","First appeal within 30 days of denial","Second appeal to CIC/SIC within 90 days","Free for BPL applicants"]',
 'RTI Act, 2005 (Act 22 of 2005)',
 '["rti","right to information","transparency","governance","citizen"]', true, now(), '[]'),
('Digital Personal Data Protection Act 2023', 'dpdp-act-2023', 'Digital',
 'The DPDP Act 2023 regulates processing of digital personal data and protects citizen privacy.',
 'The Digital Personal Data Protection (DPDP) Act, 2023 regulates the processing of digital personal data. It establishes rights for data principals (citizens) and obligations for data fiduciaries (entities processing data). It aims to protect individual privacy in the digital economy.',
 '["Consent required for data processing","Right to access, correct, erase data","Data Protection Board for grievances","Significant data fiduciaries have extra obligations","Children data requires verifiable parental consent","Penalties up to Rs. 250 crore for violations"]',
 'DPDP Act, 2023 (Act 22 of 2023)',
 '["data","privacy","digital","protection","dpdp","consent"]', true, now(), '[]'),
('Goods and Services Tax (GST) Act', 'gst-act', 'Tax',
 'GST unified indirect taxation with one tax across India for goods and services.',
 'The Goods and Services Tax (GST) Act, 2017 unified multiple indirect taxes into a single tax. It has CGST, SGST, and IGST components with rates of 0%, 5%, 12%, 18%, and 28%. GST replaced VAT, service tax, excise duty, and other indirect taxes.',
 '["Single tax for goods and services","Rates: 0%, 5%, 12%, 18%, 28%","Threshold: Rs. 20 lakh (services), Rs. 40 lakh (goods)","GSTIN: 15-digit unique ID","GST Council decides rates","Composition scheme for small businesses"]',
 'CGST Act, 2017 (Act 13 of 2017)',
 '["gst","tax","indirect","goods","services","cgst","igst"]', true, now(), '[]'),
('Labour Codes 2020', 'labour-codes-2020', 'Employment',
 'Four labour codes consolidate 29 labour laws into 4 codes covering wages, industrial relations, social security, and occupational safety.',
 'The Government of India consolidated 29 labour laws into 4 labour codes: Code on Wages, Industrial Relations Code, Social Security Code, and Occupational Safety, Health and Working Conditions Code. These codes simplify compliance and expand coverage.',
 '["Code on Wages: Universal minimum wage","Industrial Relations Code: Fixed-term employment","Social Security Code: Gig workers covered","OSH Code: Inter-state migrant workers","One license, one registration","Digital compliance and records"]',
 'Labour Codes 2020 (4 Acts of 2020)',
 '["labour","employment","wages","social security","safety","code"]', true, now(), '[]'),
('National Health Policy 2017', 'national-health-policy-2017', 'Health',
 'The National Health Policy 2017 aims to achieve universal health coverage and reduce out-of-pocket spending.',
 'The National Health Policy 2017 aims to achieve the highest possible level of health and well-being for all ages. It targets reducing out-of-pocket expenditure, increasing health spending, and achieving universal health coverage through Ayushman Bharat.',
 '["Increase health spending to 2.5% of GDP","Reduce out-of-pocket expenditure","Ayushman Bharat: PM-JAY and HWCs","Free drugs and diagnostics in public facilities","Health and wellness centers","Target: 90% immunization by 2025"]',
 'National Health Policy 2017 (Ministry of Health)',
 '["health","policy","universal","coverage","ayushman","pmjay"]', true, now(), '[]'),
('National Policy for Persons with Disabilities 2006', 'disability-policy-2006', 'Disability',
 'The policy ensures full participation and equal opportunities for persons with disabilities.',
 'The National Policy for Persons with Disabilities, 2006 recognizes that persons with disabilities are valuable human resources. It focuses on prevention, rehabilitation, and empowerment. The Rights of Persons with Disabilities (RPwD) Act, 2016 expanded rights and reservation.',
 '["7 categories expanded to 21 in RPwD Act 2016","4% reservation in government jobs","5% reservation in higher education","Accessible infrastructure mandatory","Sign language recognition","Disability certificates and UDID cards"]',
 'National Policy 2006 + RPwD Act 2016',
 '["disability","divyang","rights","reservation","accessibility","rpwd"]', true, now(), '[]'),
('National Policy for Women 2016', 'national-policy-women-2016', 'Women',
 'The policy envisions a society where women enjoy equal rights and opportunities.',
 'The National Policy for Women 2016 envisions a society where women can make choices and enjoy equal rights. It covers health, education, economy, governance, violence, and discrimination. It aims for gender mainstreaming and women empowerment.',
 '["Priority to women health and nutrition","Education and skill development","Economic empowerment and equal pay","33% reservation in police and local bodies","Zero tolerance for violence against women","Single-window support for women in distress"]',
 'National Policy for Women 2016 (Ministry of WCD)',
 '["women","policy","empowerment","gender","equality","wcd"]', true, now(), '[]'),
('National Policy on Older Persons 2011', 'national-policy-older-persons', 'Senior',
 'The policy ensures the well-being and security of senior citizens in India.',
 'The National Policy on Older Persons (NPOP) aims to ensure the well-being and security of senior citizens. It covers financial security, healthcare, shelter, and protection. The Maintenance and Welfare of Parents and Senior Citizens Act, 2007 provides legal backing.',
 '["Maintenance by children (legal obligation)","Reverse mortgage for income","Concession in travel and taxes","Old age homes in every district","Helpline for senior citizens","3% reservation in government jobs (suitable posts)"]',
 'NPOP 2011 + MWPSC Act 2007',
 '["senior","elderly","old age","maintenance","parents","policy"]', true, now(), '[]'),
('National Food Security Act 2013', 'food-security-act-2013', 'Food',
 'The NFSA guarantees food security to 75% rural and 50% urban households with subsidized grains.',
 'The National Food Security Act (NFSA), 2013 guarantees food security to 75% of rural and 50% of urban households. Beneficiaries receive 5 kg of food grains per person per month at subsidized rates. AAY families receive 35 kg per family.',
 '["75% rural, 50% urban coverage","5 kg per person per month","Rs. 1-3/kg for rice, wheat, coarse grains","AAY: 35 kg per family","Maternity benefit of Rs. 6,000","Free meals for children 6 months-6 years and pregnant women"]',
 'NFSA 2013 (Act 20 of 2013)',
 '["food","security","ration","nfsa","bpl","subsidy"]', true, now(), '[]'),
('Real Estate (Regulation and Development) Act 2016', 'rera-act-2016', 'Housing',
 'RERA protects homebuyers by regulating real estate projects and agents.',
 'The Real Estate (Regulation and Development) Act, 2016 (RERA) protects homebuyers by regulating real estate projects and agents. It mandates project registration, disclosure, and timely delivery. RERA authorities exist in every state.',
 '["Mandatory project registration with RERA","70% project funds in escrow account","Disclosure of project details","Compensation for delay","5-year structural defect warranty","RERA authority in every state"]',
 'RERA Act 2016 (Act 16 of 2016)',
 '["rera","real estate","housing","homebuyer","regulation","property"]', true, now(), '[]'),
('Insolvency and Bankruptcy Code 2016', 'ibc-act-2016', 'Business',
 'The IBC provides a time-bound framework for resolving insolvency of companies and individuals.',
 'The Insolvency and Bankruptcy Code (IBC), 2016 provides a time-bound framework for resolving insolvency of companies and individuals. It consolidates existing laws and aims to improve the ease of doing business in India.',
 '["180-day resolution timeline (extendable by 90)","Insolvency Resolution Professional (IRP) appointed","Committee of Creditors (CoC) decides","Moratorium on legal proceedings","Liquidation if no resolution","NCLT and NCLAT for adjudication"]',
 'IBC 2016 (Act 31 of 2016)',
 '["ibc","insolvency","bankruptcy","nclt","resolution","business"]', true, now(), '[]'),
('Companies Act 2013', 'companies-act-2013', 'Business',
 'The Companies Act regulates incorporation, governance, and dissolution of companies in India.',
 'The Companies Act, 2013 regulates the incorporation, governance, and dissolution of companies in India. It introduced concepts like CSR, One Person Company (OPC), and Independent Directors. The Act is administered by the Ministry of Corporate Affairs.',
 '["CSR mandatory for companies with Rs. 5 crore+ profit","One Person Company (OPC) allowed","Independent directors for listed companies","Secretarial audit for larger companies","E-governance through MCA21 portal","Class action suits by shareholders"]',
 'Companies Act 2013 (Act 18 of 2013)',
 '["companies","corporate","csr","mca","governance","business"]', true, now(), '[]'),
('FSSAI Food Safety Act 2006', 'fssai-act-2006', 'Health',
 'FSSAI regulates food safety and standards to ensure safe food for consumers.',
 'The Food Safety and Standards Act, 2006 established the Food Safety and Standards Authority of India (FSSAI). It regulates the manufacture, storage, distribution, sale, and import of food articles to ensure safe and wholesome food for consumers.',
 '["FSSAI license mandatory for food businesses","14-digit FSSAI license number on labels","Hygiene rating for restaurants","Fortification of staples (salt, oil, milk)","No-objection for imported food","Penalties for unsafe food up to Rs. 10 lakh"]',
 'FSS Act 2006 (Act 34 of 2006)',
 '["fssai","food","safety","standards","hygiene","license"]', true, now(), '[]'),
('Bharatiya Nyaya Sanhita 2023', 'bns-act-2023', 'Law',
 'BNS 2023 replaced the Indian Penal Code 1860 with modernized criminal law.',
 'The Bharatiya Nyaya Sanhita (BNS), 2023 replaced the Indian Penal Code (IPC) 1860. It modernizes criminal law with community service, electronic evidence, and organized crime provisions. It took effect from July 1, 2024.',
 '["Community service as punishment","Sedition replaced with acts endangering sovereignty","Organized crime defined","Electronic evidence admissible","Mob lynching with enhanced punishment","First-time offender leniency"]',
 'BNS 2023 (Act 45 of 2023)',
 '["bns","criminal","law","nyaya","sanhita","penal"]', true, now(), '[]'),
('Bharatiya Nagarik Suraksha Sanhita 2023', 'bnss-act-2023', 'Law',
 'BNSS 2023 replaced the Code of Criminal Procedure 1973 with modernized procedure.',
 'The Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023 replaced the Code of Criminal Procedure (CrPC) 1973. It modernizes criminal procedure with electronic FIR, video conferencing trials, and timelines for investigations.',
 '["e-FIR (online FIR registration)","Video conferencing for trials","Timeline: 90 days for chargesheet","Forensic mandatory for serious crimes","Witness protection scheme","Mercy petition timeline: 30 days"]',
 'BNSS 2023 (Act 46 of 2023)',
 '["bnss","criminal","procedure","crpc","nagarik","suraksha"]', true, now(), '[]'),
('Bharatiya Sakshya Adhiniyam 2023', 'bsa-act-2023', 'Law',
 'BSA 2023 replaced the Indian Evidence Act 1872 with modernized evidence law.',
 'The Bharatiya Sakshya Adhiniyam (BSA), 2023 replaced the Indian Evidence Act 1872. It modernizes evidence law with electronic records, admissibility of digital evidence, and joint trial provisions.',
 '["Electronic records admissible as evidence","Digital signatures recognized","Joint trial provisions","Confession to police officer inadmissible","Expert opinion expanded","Presumption of authenticity for electronic records"]',
 'BSA 2023 (Act 47 of 2023)',
 '["bsa","evidence","sakshya","adhiniyam","law","digital"]', true, now(), '[]'),
('National Cyber Security Policy 2013', 'cyber-security-policy-2013', 'Digital',
 'The policy aims to protect information and build a secure cyber ecosystem in India.',
 'The National Cyber Security Policy 2013 aims to protect information and build a secure cyber ecosystem in India. It covers protection of critical information infrastructure, incident response, and cyber security education.',
 '["Protection of critical information infrastructure","National Critical Information Protection Board","Incident response and crisis management","Cyber security education and awareness","Public-private partnership","International cooperation"]',
 'National Cyber Security Policy 2013 (MeitY)',
 '["cyber","security","policy","digital","protection","meity"]', true, now(), '[]'),
('National Policy on Disaster Management 2009', 'disaster-management-policy-2009', 'Disaster',
 'The policy provides a framework for disaster management and risk reduction in India.',
 'The National Policy on Disaster Management 2009 provides a framework for disaster management, response, and risk reduction in India. It follows the Disaster Management Act 2005 and emphasizes preparedness, mitigation, and community participation.',
 '["National Disaster Management Authority (NDMA)","State and district disaster authorities","Disaster response fund","Early warning systems","Community-based disaster management","Build back better principle"]',
 'NPDM 2009 + DM Act 2005',
 '["disaster","management","ndma","relief","risk","policy"]', true, now(), '[]'),
('National Policy on Skill Development 2015', 'skill-development-policy-2015', 'Employment',
 'The policy aims to create a skilled workforce of 400 million by 2025.',
 'The National Policy on Skill Development and Entrepreneurship 2015 aims to create a skilled workforce of 400 million by 2025. It covers vocational training, apprenticeship, and entrepreneurship development across sectors.',
 '["400 million skilled workforce by 2025","Sector Skill Councils and NSDC","National Skills Qualifications Framework (NSQF)","Apprenticeship Protsahan Yojana","Recognition of Prior Learning (RPL)","Entrepreneurship development"]',
 'National Policy on Skill Development 2015 (MSDE)',
 '["skill","development","employment","nsdc","nsqf","vocational"]', true, now(), '[]'),
('National Policy on Agriculture 2000', 'agriculture-policy-2000', 'Agriculture',
 'The policy aims for sustainable agriculture growth and food security.',
 'The National Agriculture Policy 2000 aims for sustainable agriculture growth, food security, and rural prosperity. It covers technology, investment, infrastructure, and institutional reforms in agriculture.',
 '["4% annual agriculture growth","Sustainable agriculture practices","Private sector investment","Rural infrastructure development","Land reforms and consolidation","Risk management and insurance"]',
 'National Agriculture Policy 2000 (Ministry of Agriculture)',
 '["agriculture","policy","farmer","food security","sustainable","rural"]', true, now(), '[]'),
('National Policy on Biofuels 2018', 'biofuels-policy-2018', 'Energy',
 'The policy promotes biofuels to reduce petroleum imports and support farmers.',
 'The National Policy on Biofuels 2018 promotes biofuels to reduce petroleum imports, support farmers, and reduce emissions. It expands the scope of biofuels and allows surplus food grains for ethanol production.',
 '["20% ethanol blending by 2030","5% biodiesel blending","Surplus food grains for ethanol","Used cooking oil for biodiesel","Farmers supported via biomass supply","Tax incentives for biofuel plants"]',
 'National Policy on Biofuels 2018 (Ministry of Petroleum)',
 '["biofuel","ethanol","biodiesel","energy","policy","renewable"]', true, now(), '[]'),
('National Policy on e-Commerce 2020', 'ecommerce-policy-2020', 'Digital',
 'The policy regulates e-commerce to protect consumers and promote domestic industry.',
 'The National Policy on e-Commerce 2020 regulates e-commerce marketplaces, protects consumer interests, and promotes domestic industry. It covers FDI, data localization, and anti-counterfeiting measures.',
 '["Marketplace vs inventory model","FDI only in marketplace model","Data localization for e-commerce","Anti-counterfeiting measures","Consumer grievance redressal","Level playing field for domestic sellers"]',
 'National e-Commerce Policy 2020 (DPIIT)',
 '["ecommerce","policy","digital","consumer","fdi","marketplace"]', true, now(), '[]'),
('National Policy for Rehabilitation of Bonded Labour 2016', 'bonded-labour-policy-2016', 'Rights',
 'The policy provides rehabilitation and support for rescued bonded labourers.',
 'The Central Sector Scheme for Rehabilitation of Bonded Labourer 2016 provides financial assistance, rehabilitation, and support for rescued bonded labourers. It is implemented under the Bonded Labour System (Abolition) Act 1976.',
 '["Immediate relief of Rs. 1 lakh","Rehabilitation within 3 months","Non-cash assistance for skill development","Special provisions for vulnerable groups","Survey and identification of bonded labour","Vigilance committees at district level"]',
 'Rehabilitation Scheme 2016 + BLSA Act 1976',
 '["bonded","labour","rehabilitation","rights","abolition","rescue"]', true, now(), '[]'),
('National Policy for Children 2013', 'children-policy-2013', 'Children',
 'The policy affirms the right of every child to survival, development, protection, and participation.',
 'The National Policy for Children 2013 affirms the right of every child to survival, health, nutrition, education, development, protection, and participation. It guides all laws, policies, and programs affecting children.',
 '["Right to survival, health, nutrition","Right to education and development","Right to protection from harm","Right to participation in decisions","Priority to most marginalized children","Child-friendly legal procedures"]',
 'National Policy for Children 2013 (Ministry of WCD)',
 '["children","policy","rights","protection","wcd","child"]', true, now(), '[]'),
('National Policy on Youth 2014', 'youth-policy-2014', 'Employment',
 'The policy empowers youth through education, skill development, and entrepreneurship.',
 'The National Youth Policy 2014 empowers youth through education, skill development, entrepreneurship, and health. It targets youth aged 15-29 and aligns with the 12th Five Year Plan and Sustainable Development Goals.',
 '["Youth aged 15-29 targeted","Education and skill development","Entrepreneurship and employment","Health and well-being","Social inclusion and participation","Sports and recreation promotion"]',
 'National Youth Policy 2014 (Ministry of Youth Affairs)',
 '["youth","policy","skill","employment","entrepreneurship","education"]', true, now(), '[]'),
('National Policy for Urban Housing 2015', 'urban-housing-policy-2015', 'Housing',
 'The policy aims to provide Housing for All by 2022 through affordable housing initiatives.',
 'The Pradhan Mantri Awas Yojana (PMAY) and National Policy for Urban Housing aim to provide Housing for All by 2022. It covers affordable housing, slum redevelopment, and credit-linked subsidies for EWS/LIG/MIG.',
 '["Housing for All by 2022 (now 2024)","In-situ slum redevelopment","Affordable housing in partnership","Credit-linked subsidy scheme (CLSS)","Beneficiary-led construction","EWS: Rs. 1.5 lakh subsidy, LIG: Rs. 1.5 lakh"]',
 'PMAY + Urban Housing Policy 2015 (MoHUA)',
 '["housing","urban","pmay","affordable","ews","lig","housing for all"]', true, now(), '[]'),
('National Policy for Rural Development 2018', 'rural-development-policy-2018', 'Rural',
 'The policy aims to transform rural India through livelihoods, infrastructure, and social security.',
 'The National Policy for Rural Development 2018 aims to transform rural India through livelihoods, infrastructure, and social security. It integrates MGNREGA, NRLM, PMAY-G, and other rural schemes.',
 '["MGNREGA: 100 days guaranteed wage","NRLM: Self-help groups and livelihoods","PMAY-G: Pucca houses for rural poor","NSAP: Pensions for elderly, widows, disabled","PDS: Subsidized food grains","Digital infrastructure in rural areas"]',
 'Rural Development Policy 2018 (Ministry of Rural Development)',
 '["rural","development","mgnrega","nrlm","pmay-g","livelihood"]', true, now(), '[]')
ON CONFLICT (slug) DO NOTHING;
