/*
# Expand database - Batch 2b: Citizen services

## Summary
Adds 20 common Indian citizen services with full details:
Aadhaar, PAN, Voter ID, Driving Licence, Passport, Income Certificate,
Caste Certificate, Domicile Certificate, Birth Certificate, Death Certificate,
Marriage Registration, Property Registration, Ration Card, GST Registration,
ITR Filing, Land Records, EPF, ESIC, Cybercrime Reporting, RTI, FIR, CPGRAMS.

## Notes
- Uses ON CONFLICT (slug) DO NOTHING for idempotency.
- No destructive operations; pure INSERT.
*/

-- Add a unique constraint on slug if not exists
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'citizen_services_slug_key') THEN
    ALTER TABLE citizen_services ADD CONSTRAINT citizen_services_slug_key UNIQUE (slug);
  END IF;
END $$;

INSERT INTO citizen_services (title, slug, category, description, what_is, eligibility, required_documents, fees, timeline, online_steps, offline_process, common_mistakes, faqs, official_links, checklist, tags, published, last_verified_at)
VALUES
('Aadhaar Card Enrollment', 'aadhaar-enrollment-svc', 'Identity',
 'Aadhaar is a 12-digit unique identity number issued by UIDAI to residents of India.',
 'Aadhaar is a 12-digit unique identification number issued by the Unique Identification Authority of India (UIDAI) to all residents of India. It serves as proof of identity and address.',
 'Any resident of India of any age can enroll for Aadhaar.',
 '["Proof of Identity (PAN, Voter ID, etc.)","Proof of Address (Utility bill, Bank statement, etc.)","Proof of Date of Birth (Birth certificate, SSLC certificate, etc.)"]',
 'Free for first-time enrollment. Rs. 100 for updates/corrections.',
 '7-90 days after enrollment',
 '["Visit uidai.gov.in or nearest Aadhaar enrollment center","Book an appointment online","Fill the enrollment form with correct details","Provide biometric data (fingerprints, iris scan, photograph)","Collect acknowledgment slip with enrollment ID","Check status online using Enrollment ID"]',
 'Visit any Aadhaar Seva Kendra with required documents and fill the enrollment form.',
 '["Providing incorrect address or spelling mistakes in name","Not linking mobile number with Aadhaar","Not keeping the acknowledgment slip safe"]',
 '[{"q":"Is Aadhaar mandatory?","a":"Aadhaar is not mandatory for all services but is required for many government schemes and services."},{"q":"Can NRIs apply for Aadhaar?","a":"Yes, NRIs with valid Indian passports can apply for Aadhaar."},{"q":"How to update Aadhaar details?","a":"Visit uidai.gov.in or nearest Aadhaar center to update details for a fee of Rs. 100."}]',
 '["https://uidai.gov.in","https://myaadhaar.uidai.gov.in"]',
 '["Proof of Identity","Proof of Address","Proof of Date of Birth","Mobile Number"]',
 '["aadhaar","identity","uidai","enrollment","biometric"]', true, now()),
('PAN Card Application', 'pan-card-application-svc', 'Tax',
 'Permanent Account Number (PAN) is a 10-character alphanumeric identifier issued by the Income Tax Department.',
 'PAN is a unique 10-character alphanumeric identifier issued by the Income Tax Department of India to any person who applies for it. It is mandatory for financial transactions above specified limits.',
 'Any individual, company, firm, or entity can apply for PAN.',
 '["Proof of Identity","Proof of Address","Proof of Date of Birth","2 Passport-size photographs"]',
 'Rs. 107 for physical PAN card (within India), Rs. 1,017 for delivery outside India.',
 '15-20 working days',
 '["Visit protean.utmportal.com or tin-nsdl.com","Select application type (Form 49A for citizens, 49AA for foreigners)","Fill the form with personal and contact details","Upload documents and photograph","Pay the fee online","Track status using acknowledgment number"]',
 'Submit Form 49A at any NSDL TIN Facilitation Center with required documents and fee.',
 '["Incorrect name spelling (must match proof)","Wrong date of birth","Mismatch between name and signature"]',
 '[{"q":"Is PAN mandatory?","a":"PAN is mandatory for filing income tax returns and for high-value transactions."},{"q":"Can I have multiple PAN cards?","a":"No, having multiple PAN cards is illegal and attracts a penalty of Rs. 10,000."},{"q":"How to link PAN with Aadhaar?","a":"Visit incometaxindia.gov.in and use the linking facility; it is mandatory."}]',
 '["https://www.incometaxindia.gov.in","https://www.protean-tinpan.com"]',
 '["Proof of Identity","Proof of Address","Proof of Date of Birth","Photographs"]',
 '["pan","tax","income","identity","nsdl"]', true, now()),
('Voter ID Card (EPIC)', 'voter-id-card-svc', 'Identity',
 'Voter ID (EPIC) is an identity document issued by the Election Commission to eligible voters.',
 'The Electors Photo Identity Card (EPIC), commonly known as Voter ID, is issued by the Election Commission of India to all eligible voters. It serves as proof of identity and is required to vote in elections.',
 'Indian citizen, Age 18+ as on January 1 of the year of electoral roll revision, Resident of the constituency.',
 '["Proof of Identity","Proof of Address","Proof of Age (Birth certificate, SSLC, etc.)","Passport-size photograph"]',
 'Free',
 '30-60 days',
 '["Visit voters.eci.gov.in","Register as a new voter using Form 6","Fill personal details, address, and upload documents","Submit the form and note the application ID","Track status online using application ID","Download e-EPIC after approval"]',
 'Submit Form 6 at the Electoral Registration Officer (ERO) office or Booth Level Officer (BLO) with documents.',
 '["Wrong constituency selection","Incorrect address","Not uploading clear photograph"]',
 '[{"q":"Can NRIs vote?","a":"NRIs can register as voters if they hold valid Indian passports."},{"q":"How to correct Voter ID details?","a":"Submit Form 8 online or at the ERO office for corrections."},{"q":"Can I download e-EPIC?","a":"Yes, download from voters.eci.gov.in using your EPIC number."}]',
 '["https://voters.eci.gov.in","https://www.eci.gov.in"]',
 '["Proof of Identity","Proof of Address","Proof of Age","Photograph"]',
 '["voter","epic","election","identity","voting"]', true, now()),
('Driving Licence Application', 'driving-licence-svc', 'Transport',
 'A driving licence is an official document authorizing an individual to operate a motor vehicle.',
 'A driving licence (DL) is an official document issued by the Regional Transport Office (RTO) that authorizes an individual to drive a motor vehicle on public roads in India.',
 'Age 18+ for two-wheeler (non-transport), Age 20+ for transport vehicles, Must hold a Learner Licence for 30 days.',
 '["Proof of Age","Proof of Address","Learner Licence","Passport-size photographs","Medical Certificate (for transport vehicles)"]',
 'Rs. 200 for smart card, Rs. 50 for laminated, Rs. 300 for renewal.',
 '7-30 days after test',
 '["Visit parivahan.gov.in","Select your state and RTO","Apply for Learner Licence first","Pass the Learner Licence test","Wait 30 days, apply for permanent DL","Book a slot for driving test","Pass the driving test to get DL"]',
 'Visit the RTO with Learner Licence, documents, and your vehicle for the driving test.',
 '["Not practicing enough before the test","Vehicle documents not in order","Wrong RTO jurisdiction"]',
 '[{"q":"Can I drive with a Learner Licence?","a":"Yes, with an L plate and a licensed driver beside you."},{"q":"How to renew DL?","a":"Apply for renewal within 30 days of expiry at parivahan.gov.in or RTO."},{"q":"Is an International Driving Permit available?","a":"Yes, apply at the RTO with valid Indian DL and passport."}]',
 '["https://parivahan.gov.in","https://sarathi.parivahan.gov.in"]',
 '["Proof of Age","Proof of Address","Learner Licence","Photographs"]',
 '["driving","licence","rto","transport","vehicle"]', true, now()),
('Passport Application', 'passport-application-svc', 'Identity',
 'A passport is an official travel document issued by the Government of India for international travel.',
 'A passport is an official travel document issued by the Ministry of External Affairs, Government of India, that certifies the identity and nationality of the holder for international travel.',
 'Indian citizen with valid proof of identity and address.',
 '["Proof of Identity","Proof of Address","Proof of Date of Birth","Passport-size photographs"]',
 'Rs. 1,500-3,500 for 36-page booklet (varies by type and validity)',
 '30-45 days (normal), 7-15 days (Tatkal)',
 '["Visit passportindia.gov.in","Register and create an account","Fill the application form online","Pay the fee and book an appointment","Visit Passport Seva Kendra with documents","Biometric and document verification","Police verification","Passport dispatched via Speed Post"]',
 'Visit Passport Seva Kendra on appointment day with originals and self-attested copies.',
 '["Incorrect personal details","Address mismatch with proof","Not carrying original documents"]',
 '[{"q":"What is Tatkal passport?","a":"Tatkal passport is issued in 7-15 days for an additional fee."},{"q":"How to renew passport?","a":"Apply for re-issue on passportindia.gov.in with old passport and documents."},{"q":"Can I track passport status?","a":"Yes, track on passportindia.gov.in using file number."}]',
 '["https://www.passportindia.gov.in","https://www.mea.gov.in"]',
 '["Proof of Identity","Proof of Address","Proof of Date of Birth","Photographs"]',
 '["passport","travel","identity","mea","international"]', true, now()),
('Income Certificate', 'income-certificate-svc', 'Certificate',
 'Income certificate is an official document certifying the annual income of an individual or family.',
 'An income certificate is an official document issued by the state government that certifies the annual income of an individual or family from all sources. It is required for availing various welfare schemes.',
 'Resident of the state for which the certificate is being applied.',
 '["Aadhaar Card","Proof of Address","Salary Slip (if employed)","Bank Statement (last 6 months)","Affidavit of income"]',
 'Free or nominal fee (Rs. 20-40)',
 '7-15 days',
 '["Visit the state e-district portal","Register and login","Select Income Certificate application","Fill the form with income details","Upload documents","Submit and note application ID","Download certificate when approved"]',
 'Visit the Tehsil/Mandal office with documents and submit the application form.',
 '["Under-reporting actual income","Mismatch with bank statements","Missing employer certificate"]',
 '[{"q":"What is the validity of income certificate?","a":"Typically valid for 1-3 years depending on state rules."},{"q":"Can I apply online?","a":"Yes, most states offer online application via e-district portals."},{"q":"Is income certificate required for scholarships?","a":"Yes, it is required for most scholarships and welfare schemes."}]',
 '[]',
 '["Aadhaar Card","Proof of Address","Salary Slip","Bank Statement","Affidavit"]',
 '["income","certificate","edistrict","welfare"]', true, now()),
('Caste Certificate', 'caste-certificate-svc', 'Certificate',
 'Caste certificate is an official document certifying a person''s caste for reservation benefits.',
 'A caste certificate is an official document issued by the state government that certifies a person''s caste. It is required to avail reservation benefits in education, employment, and government schemes.',
 'Person belonging to SC/ST/OBC category as per state government notification.',
 '["Aadhaar Card","Proof of Address","Birth Certificate","School Certificate showing caste","Affidavit of caste","Parent''s caste certificate (if available)"]',
 'Free or nominal fee',
 '7-30 days',
 '["Visit the state e-district portal","Select Caste Certificate application","Fill personal and caste details","Upload supporting documents","Submit and note application ID","Download certificate when approved"]',
 'Visit the Tehsil/Mandal office or Revenue officer with documents.',
 '["Caste not in state list","Mismatch with parent records","Incomplete documentation"]',
 '[{"q":"Is caste certificate valid across India?","a":"SC/ST certificates are valid across India; OBC certificates may be state-specific."},{"q":"How to renew OBC certificate?","a":"OBC certificates need renewal every 3 years; apply via e-district portal."},{"q":"Can I get caste certificate for my child?","a":"Yes, based on parents'' caste certificates and birth certificate."}]',
 '[]',
 '["Aadhaar Card","Proof of Address","Birth Certificate","School Certificate","Affidavit"]',
 '["caste","certificate","sc","st","obc","reservation"]', true, now()),
('Domicile Certificate', 'domicile-certificate-svc', 'Certificate',
 'Domicile certificate is an official document certifying a person''s residence in a state.',
 'A domicile certificate (also called residence certificate) is an official document issued by the state government that certifies a person''s residence in that state. It is required for various state-specific benefits.',
 'Person residing in the state for a minimum period (usually 3-5 years).',
 '["Aadhaar Card","Proof of Address (Utility bill, Rent agreement)","Birth Certificate","School/College leaving certificate","Employment proof (if any)"]',
 'Free or nominal fee',
 '7-30 days',
 '["Visit the state e-district portal","Select Domicile/Residence Certificate","Fill personal and residence details","Upload supporting documents","Submit and note application ID","Download certificate when approved"]',
 'Visit the Tehsil/Mandal office with documents and affidavit.',
 '["Insufficient proof of residence","Address mismatch","Missing birth certificate"]',
 '[{"q":"Is domicile certificate required for jobs?","a":"Yes, for state government jobs and state-specific schemes."},{"q":"Can I have domicile of multiple states?","a":"No, you can have domicile of only one state at a time."},{"q":"How long is it valid?","a":"Typically valid for lifetime unless circumstances change."}]',
 '[]',
 '["Aadhaar Card","Proof of Address","Birth Certificate","School Certificate"]',
 '["domicile","residence","certificate","edistrict"]', true, now()),
('Birth Certificate', 'birth-certificate-svc', 'Certificate',
 'Birth certificate is an official document recording the birth of a person.',
 'A birth certificate is an official document issued by the Municipal Corporation or local body that records the birth of a person. It serves as proof of date and place of birth, and parentage.',
 'Any person born in India; parents can register birth of their child within 21 days (free) or up to 1 year (with late fee).',
 '["Hospital discharge summary","Parents'' identity proof","Parents'' marriage certificate (if any)","Proof of address"]',
 'Free within 21 days; late fee after that',
 '7-30 days',
 '["Visit the municipal corporation portal","Select Birth Registration","Fill child and parent details","Upload hospital summary and parents'' IDs","Submit and note application ID","Download certificate when approved"]',
 'Visit the municipal office with hospital discharge summary and parents'' documents.',
 '["Not registering within 21 days","Spelling mistakes in name","Wrong date of birth"]',
 '[{"q":"Is birth certificate mandatory?","a":"Yes, it is required for school admission, passport, and other services."},{"q":"How to correct birth certificate?","a":"Apply for correction at the municipal office with supporting documents."},{"q":"Can I get birth certificate online?","a":"Yes, many states offer online download via e-district portals."}]',
 '[]',
 '["Hospital discharge summary","Parents'' identity proof","Proof of address"]',
 '["birth","certificate","municipal","registration"]', true, now()),
('Death Certificate', 'death-certificate-svc', 'Certificate',
 'Death certificate is an official document recording the death of a person.',
 'A death certificate is an official document issued by the Municipal Corporation or local body that records the death of a person. It is required for property transfer, insurance claims, and pension benefits.',
 'Any person can register a death; registration is mandatory within 21 days.',
 '["Medical certificate of death (Form 4)","Identity proof of deceased","Proof of address of deceased","Affidavit (if late registration)"]',
 'Free within 21 days; late fee after that',
 '7-30 days',
 '["Visit the municipal corporation portal","Select Death Registration","Fill deceased and informant details","Upload medical certificate and IDs","Submit and note application ID","Download certificate when approved"]',
 'Visit the municipal office with death certificate from hospital and deceased''s documents.',
 '["Not registering within 21 days","Missing medical certificate","Incorrect cause of death"]',
 '[{"q":"Is death certificate mandatory?","a":"Yes, it is required for property transfer, insurance, pension, and legal matters."},{"q":"How to get death certificate for death at home?","a":"Obtain a medical certificate from a registered medical practitioner first."},{"q":"Can I get death certificate online?","a":"Yes, many states offer online download via e-district portals."}]',
 '[]',
 '["Medical certificate of death","Identity proof of deceased","Proof of address"]',
 '["death","certificate","municipal","registration"]', true, now()),
('Marriage Registration', 'marriage-registration-svc', 'Certificate',
 'Marriage registration is the process of legally recording a marriage with the government.',
 'Marriage registration is the official process of recording a marriage with the Sub-Divisional Magistrate or Registrar of Marriages. A marriage certificate is required for visa, passport, insurance, and property matters.',
 'Both parties must be of legal age (21 for groom, 18 for bride) and must have consented to the marriage.',
 '["Aadhaar Card of both parties","Proof of address","Date of birth proof of both","Marriage photograph","Marriage invitation card","3 Passport-size photos of both","Witnesses with ID proof"]',
 'Rs. 100-500 (varies by state and religion)',
 '7-30 days',
 '["Visit the state e-district portal or municipal website","Select Marriage Registration","Fill bride and groom details","Upload documents and marriage photo","Book appointment at SDM office","Visit SDM with originals and witnesses","Collect marriage certificate"]',
 'Visit the SDM/Registrar office with documents and witnesses.',
 '["Not registering within 90 days of marriage","Missing witness","Incorrect personal details"]',
 '[{"q":"Is marriage registration mandatory?","a":"Yes, marriage registration is mandatory under the Supreme Court order of 2006."},{"q":"Can I register marriage online?","a":"You can start the application online but must visit the office for verification."},{"q":"How long is marriage certificate valid?","a":"Marriage certificate is valid for lifetime."}]',
 '[]',
 '["Aadhaar Card of both","Proof of address","Date of birth proof","Marriage photo","Witness IDs"]',
 '["marriage","registration","certificate","sdm"]', true, now()),
('Property Registration', 'property-registration-svc', 'Property',
 'Property registration is the legal process of recording property transactions with the government.',
 'Property registration is the official process of recording the transfer of property ownership with the Sub-Registrar. A registered sale deed is required for legal ownership of property.',
 'Buyer and seller must be competent adults with valid identity and property documents.',
 '["Aadhaar Card of buyer and seller","Property documents (sale deed, title deed)","Encumbrance certificate","NOC from society/bank (if applicable)","Property tax receipts","Photographs"]',
 'Stamp duty (varies by state, 5-8% of property value) + Registration fee (1%)',
 '1-7 days',
 '["Prepare the sale deed with a lawyer","Pay stamp duty online or via challan","Book appointment at Sub-Registrar office","Visit Sub-Registrar with buyer, seller, and witnesses","Biometric verification of parties","Collect registered sale deed"]',
 'Visit the Sub-Registrar office with sale deed, documents, and parties.',
 '["Under-valuing property to save stamp duty","Missing encumbrance certificate","Not checking property title"]',
 '[{"q":"Is property registration mandatory?","a":"Yes, registration is mandatory for legal ownership of property."},{"q":"Can I pay stamp duty online?","a":"Yes, most states offer online stamp duty payment via shcile.gov.in or state portals."},{"q":"How to check property records online?","a":"Visit the state land records portal (e.g., mahabhulekh.maharashtra.gov.in)."}]',
 '[]',
 '["Aadhaar Card","Property documents","Encumbrance certificate","Stamp duty receipt"]',
 '["property","registration","sale deed","sub-registrar","stamp duty"]', true, now()),
('Ration Card Application', 'ration-card-application-svc', 'Food',
 'A ration card is an official document that enables households to access subsidized food grains.',
 'A ration card is an official document issued by the state government that enables households to access subsidized food grains and other essential commodities through the Public Distribution System (PDS).',
 'Any Indian household with valid identity and address proof can apply.',
 '["Aadhaar Card of all family members","Proof of address","Income certificate (for category)","Passport-size photographs of family head"]',
 'Free',
 '15-30 days',
 '["Visit the state PDS/ration card portal","Select New Ration Card application","Fill family member details","Upload Aadhaar and address proof","Submit and note application ID","Download e-ration card when approved"]',
 'Visit the Food and Civil Supplies office with documents.',
 '["Incorrect family member details","Not linking Aadhaar of all members","Wrong category selection"]',
 '[{"q":"What are ration card categories?","a":"APL (Above Poverty Line), BPL (Below Poverty Line), AAY (Antyodaya Anna Yojana)."},{"q":"Can I apply online?","a":"Yes, most states offer online application via PDS portals."},{"q":"How to add/remove members?","a":"Apply for modification at the Food and Civil Supplies office."}]',
 '[]',
 '["Aadhaar Card of all members","Proof of address","Income certificate","Photographs"]',
 '["ration","food","pds","bpl","subsidy"]', true, now()),
('GST Registration', 'gst-registration-svc', 'Tax',
 'GST registration is mandatory for businesses with turnover above the threshold limit.',
 'Goods and Services Tax (GST) registration is mandatory for businesses with annual turnover above Rs. 20 lakh (services) or Rs. 40 lakh (goods). It provides a unique GSTIN for tax compliance.',
 'Business with turnover above threshold, Casual taxable person, E-commerce operator, Input service distributor.',
 '["PAN of business and owner","Aadhaar of owner","Proof of business address","Bank account details","Digital signature","Constitution documents (Partnership deed, MOA, etc.)"]',
 'Free',
 '7-10 working days',
 '["Visit gst.gov.in","Click New Registration","Fill Part A with PAN, email, mobile","Verify OTP","Fill Part B with business details","Upload documents","Submit application","Receive GSTIN after verification"]',
 'GST registration is entirely online; no offline process.',
 '["Wrong business address","Mismatched PAN and Aadhaar","Not uploading required documents"]',
 '[{"q":"Is GST registration mandatory?","a":"Yes, if your turnover exceeds the threshold limit."},{"q":"What is GSTIN?","a":"GSTIN is a 15-digit unique identification number assigned after registration."},{"q":"How to cancel GST registration?","a":"Apply for cancellation on gst.gov.in; GSTIN is suspended."}]',
 '["https://www.gst.gov.in"]',
 '["PAN","Aadhaar","Proof of business address","Bank details","Digital signature"]',
 '["gst","tax","business","registration","gstin"]', true, now()),
('Income Tax Return Filing', 'itr-filing-svc', 'Tax',
 'Filing Income Tax Return (ITR) is mandatory for individuals with income above the taxable limit.',
 'Income Tax Return (ITR) is a form used to declare income, deductions, and tax paid to the Income Tax Department. Filing ITR is mandatory for individuals with income above the basic exemption limit.',
 'Individual with annual income above Rs. 2.5 lakh (below 60), Rs. 3 lakh (60-80), Rs. 5 lakh (80+).',
 '["PAN","Aadhaar","Form 16 (from employer)","Bank statements","Investment proofs (80C, 80D)","TDS certificates (Form 16A)","Rental income details (if any)"]',
 'Free (self-filing on incometaxindia.gov.in); CA may charge Rs. 500-5000',
 'Due by July 31 each year',
 '["Visit incometaxindia.gov.in","Login with PAN and password","Select ITR form (ITR-1 for salaried)","Fill income details from Form 16","Claim deductions under 80C, 80D, etc.","Compute tax payable/refund","Verify using Aadhaar OTP or net banking","Submit and download ITR-V"]',
 'Download ITR form, fill offline, and submit at the Income Tax office (rarely used now).',
 '["Wrong ITR form selection","Not declaring all income","Missing deductions","Not verifying after filing"]',
 '[{"q":"Is ITR filing mandatory?","a":"Yes, if your income exceeds the basic exemption limit."},{"q":"What happens if I miss the deadline?","a":"You can file a belated return by December 31 with a late fee of up to Rs. 5,000."},{"q":"How to get a refund?","a":"Refunds are credited to your bank account after processing; ensure correct bank details."}]',
 '["https://www.incometaxindia.gov.in","https://www.incometaxindiaefiling.gov.in"]',
 '["PAN","Aadhaar","Form 16","Bank statements","Investment proofs"]',
 '["itr","income tax","return","filing","tax"]', true, now()),
('Land Records (Bhulekh)', 'land-records-bhulekh-svc', 'Property',
 'Land records (Bhulekh) provide official information about land ownership and details.',
 'Land records (Bhulekh) are official documents maintained by the Revenue Department that record land ownership, area, type, and other details. They are required for property transactions and legal matters.',
 'Any person who owns land or wants to verify land records can access them.',
 '["Survey number","Khata number","Owner name","District and village details"]',
 'Free (online viewing)',
 'Instant (online)',
 '["Visit the state land records portal (e.g., bhulekh.up.nic.in)","Select district and tehsil","Enter khata or survey number","View land records online","Download Record of Rights (ROR)"]',
 'Visit the Tehsil office with survey number and request land records.',
 '["Wrong survey number","Incorrect district selection","Records not updated"]',
 '[{"q":"Are land records available online?","a":"Yes, most states have digitized land records accessible via state portals."},{"q":"What is ROR?","a":"Record of Rights (ROR) is the official document showing land ownership and details."},{"q":"How to correct land records?","a":"Apply for mutation at the Tehsil office with sale deed and documents."}]',
 '[]',
 '["Survey number","Khata number","Owner name","District details"]',
 '["land","records","bhulekh","property","ror"]', true, now()),
('EPF Account (Employees Provident Fund)', 'epf-account-svc', 'Employment',
 'EPF is a retirement benefit scheme for salaried employees in India.',
 'Employees Provident Fund (EPF) is a retirement benefit scheme managed by the Employees Provident Fund Organisation (EPFO). Both employee and employer contribute 12% of basic salary to the EPF account.',
 'Employees of organizations with 20+ employees, Basic salary up to Rs. 15,000 (mandatory), above is optional.',
 '["UAN (Universal Account Number)","Aadhaar","Bank account details","PAN"]',
 'Free (employer contributes)',
 'Lifelong (until withdrawal)',
 '["Visit epfindia.gov.in","Activate UAN using PAN, Aadhaar, and mobile","Login to EPFO portal with UAN and password","Fill KYC details (Aadhaar, bank, PAN)","Check passbook and contributions","File claims for withdrawal/transfer online"]',
 'Visit EPFO office with UAN and documents for offline claims.',
 '["Not activating UAN","Mismatch in KYC details","Not linking Aadhaar with UAN"]',
 '[{"q":"What is UAN?","a":"Universal Account Number (UAN) is a 12-digit unique number for EPF members."},{"q":"Can I withdraw EPF?","a":"Yes, you can withdraw EPF for housing, medical, education, or after unemployment."},{"q":"How to check EPF balance?","a":"Check via EPFO portal, UMANG app, or SMS to 7738299899."}]',
 '["https://www.epfindia.gov.in","https://unifiedportal-mem.epfindia.gov.in"]',
 '["UAN","Aadhaar","Bank details","PAN"]',
 '["epf","provident fund","retirement","epfo","employee"]', true, now()),
('ESIC Card (Employees State Insurance)', 'esic-card-svc', 'Health',
 'ESIC provides health insurance and social security to workers earning up to Rs. 21,000 per month.',
 'Employees State Insurance Corporation (ESIC) provides health insurance, sickness, maternity, and disability benefits to workers earning up to Rs. 21,000 per month. Both employer and employee contribute.',
 'Employees of covered establishments earning up to Rs. 21,000 per month.',
 '["Aadhaar","Photograph","Bank account details","Family member details"]',
 'Employee: 0.75% of wages, Employer: 3.25% of wages',
 'Immediate (on enrollment)',
 '["Visit esic.in","Employer registers establishment","Add employee details and family members","Generate ESIC e-Pehchan card","Employee can visit ESIC dispensaries and hospitals","File claims for sickness, maternity, disability"]',
 'Visit ESIC branch office with documents.',
 '["Not adding family members","Wrong wage details","Not using ESIC dispensaries"]',
 '[{"q":"What is ESIC?","a":"ESIC provides health insurance and social security to low-wage workers."},{"q":"Can family members use ESIC?","a":"Yes, registered family members are eligible for ESIC benefits."},{"q":"How to find ESIC hospital?","a":"Visit esic.in and use the hospital locator."}]',
 '["https://www.esic.in"]',
 '["Aadhaar","Photograph","Bank details","Family details"]',
 '["esic","health","insurance","employee","worker"]', true, now()),
('Cybercrime Reporting', 'cybercrime-reporting-svc', 'Safety',
 'Report cybercrimes including online fraud, hacking, and cyberstalking through the National Cyber Crime Reporting Portal.',
 'The National Cyber Crime Reporting Portal (cybercrime.gov.in) allows citizens to report cybercrimes including online financial fraud, hacking, cyberstalking, and child pornography. Complaints are forwarded to relevant law enforcement.',
 'Any citizen who has been a victim of or witness to cybercrime.',
 '["Aadhaar","Details of the incident","Screenshots/evidence","Bank details (if financial fraud)","FIR copy (if filed)"]',
 'Free',
 'Immediate (complaint registered)',
 '["Visit cybercrime.gov.in","Select Report Cyber Crime","Choose category (women/child, financial fraud, other)","Fill complaint details","Upload evidence","Submit and note complaint ID","Track status online"]',
 'Visit nearest police station or cybercrime cell to file a complaint.',
 '["Not preserving evidence","Delay in reporting","Not providing complete details"]',
 '[{"q":"What is the cybercrime helpline?","a":"Call 1930 for financial cyber fraud (within 2 hours for best response)."},{"q":"Can I report anonymously?","a":"Yes, you can report anonymously on cybercrime.gov.in."},{"q":"How to track complaint?","a":"Track using complaint ID on cybercrime.gov.in."}]',
 '["https://cybercrime.gov.in","https://www.cybercrime.gov.in"]',
 '["Aadhaar","Incident details","Evidence","Bank details","FIR copy"]',
 '["cybercrime","fraud","cyber","report","safety","1930"]', true, now()),
('RTI Application', 'rti-application-svc', 'Rights',
 'Right to Information (RTI) allows citizens to request information from government departments.',
 'The Right to Information (RTI) Act, 2005 empowers citizens to request information from public authorities. Any citizen can file an RTI application to get information about government functioning.',
 'Any Indian citizen can file an RTI application.',
 '["Application fee (Rs. 10 for central, varies for state)","Clear description of information sought","Address of the public authority"]',
 'Rs. 10 (central government), varies by state; free for BPL',
 '30 days (48 hours if life/liberty involved)',
 '["Identify the public authority holding the information","Write the application with clear questions","Pay the application fee (court fee stamp or IPO)","Submit to the Public Information Officer (PIO)","Receive information within 30 days","If denied, file first appeal within 30 days","If still denied, file second appeal to CIC/SIC"]',
 'Submit the application by hand or post to the PIO of the concerned department.',
 '["Vague questions","Wrong department","Not paying the fee"]',
 '[{"q":"What is the RTI fee?","a":"Rs. 10 for central government, varies for state governments. BPL applicants are exempt."},{"q":"What if RTI is denied?","a":"File first appeal within 30 days, then second appeal to CIC/SIC within 90 days."},{"q":"Can I file RTI online?","a":"Yes, for central government via rtionline.gov.in; many states also offer online filing."}]',
 '["https://rtionline.gov.in"]',
 '["Application fee","Clear questions","Address of public authority"]',
 '["rti","right to information","transparency","governance"]', true, now()),
('Police FIR Registration', 'fir-registration-svc', 'Safety',
 'A First Information Report (FIR) is a written document prepared by police upon receiving information about a cognizable offense.',
 'A First Information Report (FIR) is a written document prepared by the police when they receive information about a cognizable offense (serious crime). It is the first step in the criminal justice process.',
 'Any person who has information about a cognizable offense can register an FIR.',
 '["Identity proof","Details of the incident","Witness statements (if any)","Medical report (if injury)"]',
 'Free',
 'Immediate (must be registered on receipt)',
 '["Visit the state police portal or police station","Select File FIR or Zero FIR","Fill incident details, date, time, location","Upload evidence if available","Submit and receive FIR copy","If refused, send complaint to SP/DCP","Zero FIR can be filed at any police station"]',
 'Visit the police station, provide information, and the police will register the FIR.',
 '["Not having incident details","Delay in reporting","Police refusing to register (illegal)"]',
 '[{"q":"What is a Zero FIR?","a":"A Zero FIR can be filed at any police station regardless of jurisdiction; it is later transferred to the relevant station."},{"q":"What if police refuse to register FIR?","a":"Send complaint to Superintendent of Police or file under Section 156(3) CrPC in court."},{"q":"Can I file FIR online?","a":"Yes, many states offer online FIR filing via state police portals."}]',
 '[]',
 '["Identity proof","Incident details","Witness statements","Medical report"]',
 '["fir","police","crime","safety","zero fir"]', true, now()),
('Public Grievance Registration (CPGRAMS)', 'cpgrams-grievance-svc', 'Grievance',
 'CPGRAMS is the Centralized Public Grievance Redress and Monitoring System for filing complaints against government departments.',
 'The Centralized Public Grievance Redress and Monitoring System (CPGRAMS) is an online platform where citizens can file complaints (grievances) against any central government department or ministry.',
 'Any citizen can file a grievance against a central government department or ministry.',
 '["Aadhaar (optional)","Details of the grievance","Department/ministry name","Supporting documents"]',
 'Free',
 '30-60 days for resolution',
 '["Visit pgportal.gov.in","Register and login","Select Lodge Grievance","Choose ministry/department","Fill grievance details","Upload supporting documents","Submit and note grievance ID","Track status online"]',
 'Send grievance by post to the Department of Administrative Reforms and Public Grievances.',
 '["Vague grievance description","Wrong department selection","Not providing contact details"]',
 '[{"q":"What is CPGRAMS?","a":"CPGRAMS is the central government''s online grievance redressal system."},{"q":"How long does resolution take?","a":"Departments must respond within 30-60 days."},{"q":"Can I appeal?","a":"Yes, if unsatisfied, file an appeal on pgportal.gov.in within 30 days."}]',
 '["https://pgportal.gov.in"]',
 '["Aadhaar","Grievance details","Department name","Supporting documents"]',
 '["grievance","cpgrams","complaint","government","pgportal"]', true, now())
ON CONFLICT (slug) DO NOTHING;
